POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json



//login
###
POST http://localhost:9000/api/users/login HTTP/1.1
Content-Type: application/json


//add favorite

###
PUT http://localhost:9000/api/users/favorites/63aa8c0d4760dd949eb213c6 HTTP/1.1
  Content-Type: application/json

// get favorites ok
###
GET http://localhost:9000/api/users/favorites/63ac665a5da60c6cbd3f0bd0 HTTP/1.1

// delete favorite ok
###
DELETE  http://localhost:9000/api/users/favorites/63aa5884c6125ee2b4430858 HTTP/1.1
  Content-Type: application/json

###
GET http://localhost:9000/api/users HTTP/1.1


###
GET http://localhost:9000/api/users/63adc9ea44fe711fe6463d4f HTTP/1.1

###
DELETE http://localhost:9000/api/users/63aa5a1eedf4099b5c9e3536 HTTP/1.1

###
PUT http://localhost:9000/api/users/63aa5a1eedf4099b5c9e3536 HTTP/1.1
Content-Type: application/json
